### ISSUE TITLE
Blacklist structures

### ISSUE THREAD

**Issue by Dissss1** [mactso/StructureControlUtility#1]
hello can i blacklist structures like mineshafts and meteors?

**Comment by mactso** [comment]
I don't believe so. 

I'll see about adding that tonight.

**Comment by Dissss1** [comment]
is there an update coming to blacklist blocks and stucturs?

**Comment by mactso** [comment]
Hi, the new version is out and you can now configure any structure.  By default mineshafts and villages are not protected (but they could be).

"Soft blocks" are no longer protected along with treasure blocks and ore blocks.    I will try to add tags and blocks to a configuration file at some point but I think adding unique lists by structure might be too confusing for users.

Enjoy!

**Comment by mactso** [comment]
Good suggestion!   I'll close this issue for now.
