### ISSUE TITLE
Crashing After add a custom csv file into server/config/structurecontrolutility

### ISSUE THREAD

**Issue by Git-Reternos** [mactso/StructureControlUtility#2]
Maybe I did something wrong or there is a issue
![螢幕擷取畫面 2024-07-26 043541](https://github.com/user-attachments/assets/4bd72a9d-2a28-4769-926b-78ed15c81371)

[crash-2024-07-25_20.31.57-server.txt](https://github.com/user-attachments/files/16383522/crash-2024-07-25_20.31.57-server.txt)

**Comment by mactso** [comment]
Please attach your structures.csv

**Comment by mactso** [comment]
This was an issue with Linux vs Windows and my use of the IBM string tokenizer library instead of the Java string Tokenizer library.  I switched to the Java library.  It should be fixed now.

**Comment by Git-Reternos** [comment]
Thanks for the hot fix. It solves my issues
